version: '3.7'

services:


  #Backend
  face-recon-api:
    container_name: backend
    image: node:10.15.0
    command: bash -c "npm install && npm start"
    working_dir: /usr/src/hypersnab-api
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/hypersnab-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://hypersnab:hypersnab@postgres:5432/hypersnab
      REDIS_URL: redis://redis:6379


  #Postges
  postgres:
    environment:
      POSTGRES_USER: hypersnab
      POSTGRES_PASSWORD: hypersnab
      POSTGRES_DB: hypersnab
      POSTGRES_HOST: postgres
      POSTGRES_URL: postgres://hypersnab:hypersnab@localhost:5432/hypersnab
    build: ./postgres
    ports:
      - "5433:5432"


  #Redis
  redis:
    image: redis
    ports:
      - "6379:6379"